#!/bin/bash
# Class-conditioning diagnostic pipeline orchestrator.
#
# Given a JiT checkpoint, runs in order:
#   1) jit/probe_conditioning.py     — per-class cfg_signal probe at multiple t values
#   2) jit/inspect_weights.py        — embedder geometry + AdaLN gate stats
#   3) jit/diagnose_class_diversity.py — DINOv2-based intra-class diversity vs cfg
#
# Layout produced:
#   output/diagnostics/<run_id>/
#       probe/cond_probe_t{NNN}_per_class.json
#       weights/...
#       diversity/...
#       SUMMARY.md
#
# `run_id` = <ckpt_parent_dir>_<ckpt_stem>, e.g. for
# `output/jit_JiT-B_8_full_improved_renderprobe/0260000.pt` →
# `jit_JiT-B_8_full_improved_renderprobe_0260000`.
#
# Usage:
#   ./jit/run_diagnostics.sh <checkpoint.pt> [--skip-diversity] [--t-values "0.3 0.5 0.7"]
#
# Env:
#   PROBE_T_VALUES   — override default t value list (default "0.3 0.5 0.7")
#   PROBE_T_FOR_XREF — t value to use for inspect_weights / diversity (default 0.5)
#   SKIP_DIVERSITY=1 — same as --skip-diversity flag

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <checkpoint.pt> [--skip-diversity] [--t-values \"0.3 0.5 0.7\"]" >&2
    exit 1
fi

CKPT="$1"
shift

if [ ! -f "$CKPT" ]; then
    echo "Checkpoint not found: $CKPT" >&2
    exit 1
fi

PROBE_T_VALUES="${PROBE_T_VALUES:-0.3 0.5 0.7}"
PROBE_T_FOR_XREF="${PROBE_T_FOR_XREF:-0.5}"
SKIP_DIVERSITY="${SKIP_DIVERSITY:-0}"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --skip-diversity)
            SKIP_DIVERSITY=1
            shift
            ;;
        --t-values)
            PROBE_T_VALUES="$2"
            shift 2
            ;;
        *)
            echo "Unknown flag: $1" >&2
            exit 1
            ;;
    esac
done

# Derive run_id and output paths to match jit/_diag_paths.py.
CKPT_DIR_NAME="$(basename "$(dirname "$(realpath "$CKPT")")")"
CKPT_STEM="$(basename "$CKPT" .pt)"
RUN_ID="${CKPT_DIR_NAME}_${CKPT_STEM}"
OUT_ROOT="output/diagnostics/${RUN_ID}"
PROBE_DIR="${OUT_ROOT}/probe"
WEIGHTS_DIR="${OUT_ROOT}/weights"
DIVERSITY_DIR="${OUT_ROOT}/diversity"

mkdir -p "$OUT_ROOT" "$PROBE_DIR" "$WEIGHTS_DIR"
[ "$SKIP_DIVERSITY" = "1" ] || mkdir -p "$DIVERSITY_DIR"

echo "============================================================"
echo "Diagnostic pipeline"
echo "  checkpoint:         $CKPT"
echo "  run_id:             $RUN_ID"
echo "  output root:        $OUT_ROOT"
echo "  probe t values:     $PROBE_T_VALUES"
echo "  cross-ref t value:  $PROBE_T_FOR_XREF"
echo "  diversity:          $([ "$SKIP_DIVERSITY" = "1" ] && echo skipped || echo enabled)"
echo "============================================================"

# Activate venv if not already active.
if [ -z "${VIRTUAL_ENV:-}" ] && [ -f .3dgen/bin/activate ]; then
    # shellcheck disable=SC1091
    source .3dgen/bin/activate
fi

# 1) Probe (writes per-class JSONs for every t value into PROBE_DIR).
echo
echo ">>> [1/3] Probe conditioning signal"
python jit/probe_conditioning.py \
    --checkpoint "$CKPT" \
    --t_values $PROBE_T_VALUES \
    --per_class_dump_dir "$PROBE_DIR" \
    | tee "${PROBE_DIR}/probe_log.txt"

# 2) Weight inspection (consumes per-class JSON at PROBE_T_FOR_XREF).
echo
echo ">>> [2/3] Weight inspection"
python jit/inspect_weights.py \
    --checkpoint "$CKPT" \
    --out_dir "$WEIGHTS_DIR" \
    --cfg_per_class_t "$PROBE_T_FOR_XREF" \
    | tee "${WEIGHTS_DIR}/inspect_log.txt"

# 3) Diversity (DINOv2 features, expensive; cache shared across runs).
if [ "$SKIP_DIVERSITY" = "1" ]; then
    echo
    echo ">>> [3/3] Diversity diagnosis SKIPPED"
else
    echo
    echo ">>> [3/3] Diversity diagnosis"
    python jit/diagnose_class_diversity.py \
        --checkpoint "$CKPT" \
        --out_dir "$DIVERSITY_DIR" \
        --probe_t "$PROBE_T_FOR_XREF" \
        | tee "${DIVERSITY_DIR}/diversity_log.txt"
fi

# Top-level pointer document so future-you can find everything.
cat > "${OUT_ROOT}/SUMMARY.md" <<EOF
# Diagnostic run: ${RUN_ID}

Checkpoint: \`${CKPT}\`
Generated by: \`jit/run_diagnostics.sh\`
Probe t values: \`${PROBE_T_VALUES}\`
Cross-reference t value: \`${PROBE_T_FOR_XREF}\`

## Subdirectories

- \`probe/\`     — per-class cfg_signal JSONs and the probe log. See \`cond_probe_t*_per_class.json\`.
- \`weights/\`   — embedder geometry + AdaLN gate stats. See \`weights/SUMMARY.md\` if regenerated by hand, else read \`inspection_bundle.json\` and \`adaln_proj_norms.png\`.
- \`diversity/\` — DINOv2 intra-class diversity vs cfg_signal. See \`correlation_summary.json\`, \`diversity_vs_cfg_scatter.png\`, \`weak_partition.json\`, and \`visual_sanity_grid.png\`.

For interpretation guidance see \`docs/diagnostics.md\`.
EOF

echo
echo "Done. Top-level pointer: ${OUT_ROOT}/SUMMARY.md"
